### PR TITLE
Adjust timeMax parameter for event calendar

### PR DESCRIPTION
**Pull request by kylesaburao**
Add a year for the event filter

### CODE REVIEW

**Comment by kylesaburao** [comment]
maximum set for current term

**Comment by marcusgchan** [comment]
Should we auto set it to the next year with '''getFullDate()''' so we don't forget in the future or would that cause other problems?

**Comment by kylesaburao** [comment]
> Should we auto set it to the next year with getFullDate() so we don't forget in the future or would that cause other problems?

I'm thinking it should be fixed for the current executive year.
A later change would have us read from a config JSON that is described in the README, instead of it being hardcoded here.

**Comment by kylesaburao** [comment]
Having a fixed window would reduce the network call size from Google's end, but we could later on have some button that lets us pull everything from the beginning.

**Review by dannyl1u — APPROVED** [review]

**Pull request merged**
