### PR TITLE
Add instagram feed using EmbedSocialWidget

### PR DESCRIPTION
**Pull request by brianrahadi**
Add an Instagram feed to the main page to increase website traffic and redirect more people to Instagram.
Utilized [EmbedSocial](https://embedsocial.com/) third-party library since embedding Instagram manually is a bit complicated. Since this uses a free plan, the layout, and style cannot be customized.

The design uses a carousel that also slides automatically. I think having 3 big posts are a good option since we want to emphasize the latest post, this comes with a slider and the user can still view the other posts. 

Other free alternative:
- https://behold.so/

Screenshot 1:
image

Screenshot 2 - Hover:
image

### CODE REVIEW

**Comment by brianrahadi** [comment]
The only thing that bothers me about using this tool is that we can't change the following button color, so it clashes a bit with the theme of the website. I can try checking behold.so too since that one is more flexible to use.

**Review by KiaanCastillo — CHANGES_REQUESTED** [review]
Looks great! Is there a way to remove the header with the profile pic + follow button so it's only just the posts? Also can we add padding on the left and right sides of the container for the `EmbedSocialWidget` component to match the padding for the rest of the site?

**Comment by brianrahadi** [comment]
@KiaanCastillo Thanks for the review! I will investigate further but from what I remember, there isn't a way to do so. The colour difference kinda make me rethink if this is the worthwhile approach hmm.

**Comment by brianrahadi** [comment]
Closed because the color cannot be changed and design is quite different from the figma ones.

**Pull request closed without merging**
